#!/usr/bin/env bash
# Post a validation report as a PR comment, replacing any previous reports.
#
# Usage: 06-post-report.sh <repo> <pr_number> <report_file_or_stdin>
#
#   repo        GitHub repo in owner/repo format (e.g., commontk/CTK or Slicer/Slicer)
#   pr_number   PR number to comment on
#   report      Path to report file, or "-" to read from stdin
#
# This script:
#   1. Finds all previous comments containing the /ctk-validate-pr signature
#   2. Replaces their body with an "Outdated report removed" notice
#   3. Posts the new report as a fresh comment
#
# Exit code: 0 on success, 1 on failure
set -euo pipefail

REPO="${1:?Usage: $0 <repo> <pr_number> <report_file_or_->}"
PR_NUM="${2:?Usage: $0 <repo> <pr_number> <report_file_or_->}"
REPORT_SOURCE="${3:--}"

SIGNATURE="Generated by \`/ctk-validate-pr\` skill"
OUTDATED_BODY="~~**/ctk-validate-pr** report superseded by a newer validation run.~~"

########################################################################
# Step 1: Find and replace previous report comments
########################################################################
echo "Searching for previous /ctk-validate-pr comments on ${REPO}#${PR_NUM}..."

# Get all comments, filter for ones containing our signature
COMMENT_IDS=$({ gh api "repos/${REPO}/issues/${PR_NUM}/comments" --paginate --jq '.[] | select(.body | test("Generated by `/ctk-validate-pr` skill")) | .id' 2>/dev/null || true; })

if [ -n "${COMMENT_IDS}" ]; then
  COMMENT_COUNT=$(echo "${COMMENT_IDS}" | wc -l | tr -d ' ')
  echo "Found ${COMMENT_COUNT} previous report(s) to mark as outdated."
  for CID in ${COMMENT_IDS}; do
    echo "  Updating comment ${CID}..."
    gh api "repos/${REPO}/issues/comments/${CID}" \
      -X PATCH \
      -f body="${OUTDATED_BODY}" \
      --silent 2>&1 || echo "  WARNING: Failed to update comment ${CID}"
  done
else
  echo "No previous reports found."
fi

########################################################################
# Step 2: Post the new report
########################################################################
echo "Posting new report..."
if [ "${REPORT_SOURCE}" = "-" ]; then
  # Read from stdin
  REPORT_BODY=$(cat)
else
  REPORT_BODY=$(cat "${REPORT_SOURCE}")
fi

COMMENT_URL=$(echo "${REPORT_BODY}" | gh pr comment "${PR_NUM}" --repo "${REPO}" --body-file -)
echo "Posted: ${COMMENT_URL}"
